### ISSUE TITLE
Error: `by` can't contain join column `package_id` which is missing from LHS

### ISSUE THREAD

**Issue by Edouard-Legoupil** [callumgwtaylor/hdxr#12]
Hi,

Was testing the package 

```
 library(hdxr)
 acled <- hdx_dataset_search(term = "acled") %>%
   hdx_resource_list() %>%
   hdx_resource_csv()
```
gave me the following : 

> Error: `by` can't contain join column `package_id` which is missing from LHS

Not sure what the pb is...

**Comment by Edouard-Legoupil** [comment]
and
` hdx_dataset_search(term = "acled", exact = TRUE)`
gives

> Error in UseMethod("filter_") : 
>   no applicable method for 'filter_' applied to an object of class "list"

**Comment by dickoa** [comment]
Hi Edouard,

You need to call `hdx_connect` first

 ```
library(hdxr)
library(magrittr) ## for %>%
 hdx_connect()

 acled <- hdx_dataset_search(term = "acled") %>%
   hdx_resource_list() %>%
   hdx_resource_csv()
```

Or if you are familiar with the `ckanr` package

`ckanr_setup(url = "http://data.humdata.org")`

Let me know if it works

Best,

**Comment by callumgwtaylor** [comment]
Hi Eduoard,

@dickoa has it entirely correct. Both of his suggestions will get rid of the problem you're having. I'll close this issue for now but please do contact if you have any other problems or suggestions.
