### ISSUE TITLE
Example hdx_resource_csv not working

### ISSUE THREAD

**Issue by david-hammond** [callumgwtaylor/hdxr#14]
If I run the example code

afghanistan <- hdx_dataset_search(term = "ocha-afghanistan-topline-figures") %>%
  hdx_resource_list() %>%
  hdx_resource_csv()

I get the following error message

Error: The LHS of `:=` must be a string or a symbol
Call `rlang::last_error()` to see a backtrace.
In addition: Warning message:
`.key` is deprecated

**Comment by dickoa** [comment]
Hi @david-hammond 

I hope all is good, it's not a fix and I can check with @callumgwtaylor how to help on that.
However, I also built a package named `rhdx` with the same purpose, you can also give it a try in the meantime. 

It's available here:
https://github.com/dickoa/rhdx

```{r}
library(rhdx)
library(dplyr)

set_rhdx_config()

afgh_top_fig <- pull_dataset("ocha-afghanistan-topline-figures") %>%
  get_resource(index = 1) %>% ## read the first resource (only one here)
  read_resource() ## you can read it directly or download with "download_resource"

glimpse(afgh_top_fig)
## Observations: 4
## Variables: 9
## $ code        <chr> "ocha_afg_01", "ocha_afg_02", "ocha_afg_03…
## $ title       <chr> "Conflict-induced IDPs (01 Jan - 06 Nov 20…
## $ value       <dbl> 380300, 434000, 295700, 3812
## $ latest_date <date> 2019-11-06, 2019-11-09, 2019-09-29, 2019-…
## $ source      <chr> "Multiple Sources", "IOM & UNHCR", "Multip…
## $ source_link <chr> "https://data.humdata.org/dataset/ocha-afg…
## $ notes       <chr> "Number of conflict induced IDPs", "Number…
## $ explore     <lgl> NA, NA, NA, NA
## $ units       <chr> "count", "count", "count", "count"

```
Thanks

**Comment by callumgwtaylor** [comment]
Hi @david-hammond and @dickoa 

Sorry I think the package is probably deprecated, it relies on a lot of tidyverse stuff that has probably changed since posting. I'd recommend using @dickoa 's package if his is up to date, as I'm not too certain when I'll get a chance to review and update this one!

Thanks, Callum
